# Generated by Django 6.0.1 on 2026-01-07 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RfidCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="UID Karty"
                    ),
                ),
                ("exipiry_date", models.DateTimeField(verbose_name="Ważna do")),
                ("valid", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="EntryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid_raw",
                    models.CharField(max_length=50, verbose_name="Odczytany UID"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GRANTED", "Access Granted"),
                            ("DENIED_EXPIRED", "Denied (Expired)"),
                            ("DENIED_UNKNOWN", "Denied (Unknown Card)"),
                            ("DENIED_INACTIVE", "Denied (Card Inactive)"),
                        ],
                        default="DENIED_UNKNOWN",
                        max_length=20,
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.rfidcard",
                    ),
                ),
            ],
        ),
    ]
