# Generated by Django 5.2.2 on 2026-01-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cardholder_rfidcard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardholder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entrylog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entrylog',
            name='status',
            field=models.CharField(choices=[('GRANTED', 'Access Granted'), ('DENIED_EXPIRED', 'Denied (Expired)'), ('DENIED_UNKNOWN', 'Denied (Unknown Card)'), ('DENIED_INACTIVE', 'Denied (Card Inactive)'), ('REGISTERED', 'Registered (New Card)'), ('UPDATED', 'Updated')], default='DENIED_UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='rfidcard',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
